### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SyedRafayAbrar** [stemword/php-inventory-management-system#1]
product is not adding in the product table. it stucks on loading...

**Comment by stemword** [comment]
Hi,
I try to reproduce the issue but a product is adding properly. Will you send me a screenshot of error or steps to reproduce it?

**Comment by SyedRafayAbrar** [comment]
Sorry product is added successfully but the order is not placing , it is only effecting our product quantity but not placing an order.

**Comment by estoyomar** [comment]
Hi,
I am new to this world. Can you tell me how can I login? Or how can i change the admin password and username?

Thank you.

**Comment by sumitgalaxy** [comment]
Adding new row at the time of add new order , is not working on online server, but works on localhost. In online server it stuck to loading...
Can you help me in this matter.
Thanking you in advance.

**Comment by amine-louni** [comment]
i think the problem is with php version

**Comment by oneprobanana** [comment]
Check you have write permissions to the asset folder.  Also make sure you have permissions to the "store" schema.
