### ISSUE TITLE
How to change vat valu

### ISSUE THREAD

**Issue by charan379** [stemword/php-inventory-management-system#11]

**Comment by VoltaTrainee** [comment]
Can you help me with this error 
Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\php-inventory-management-system-master\php_action\db_connect.php on line 9
Connection Failed : Access denied for user 'root'@'localhost' (using password: YES)

**Comment by stemword** [comment]
Please go to db_connection.php and change password.
