### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by VoltaTrainee** [stemword/php-inventory-management-system#12]
Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\php-inventory-management-system-master\php_action\db_connect.php on line 9
Connection Failed : Access denied for user 'root'@'localhost' (using password: YES)

**Comment by stemword** [comment]
Go to db_connect.php and change password.
