### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by prisqia** [stemword/php-inventory-management-system#13]
Parse error: syntax error, unexpected 'Connection' (T_STRING) in C:\xampp\htdocs\php-inventory-management-system-master\php_action\db_connect.php on line 11

What should i do? im sorry, im really new at this

**Comment by stemword** [comment]
Might be database details are wrong or please attach a screenshot of error and code.

**Comment by prisqia** [comment]
![1591884999288](https://user-images.githubusercontent.com/66578157/84397541-ef333000-ac28-11ea-8f1a-9bd65322db17.jpg)

Like that

**Comment by stemword** [comment]
`<?php 	

$localhost = "localhost";
$username = "root";
$password = "root";
$dbname = "store";
$store_url = "http://localhost/php-inventory-management-system/";
// db connection
$connect = new mysqli($localhost, $username, $password, $dbname);
// check connection
if($connect->connect_error) {
  die("Connection Failed : " . $connect->connect_error);
} else {
   echo "Successfully connected";
}

?>`

change like this. As your store URL is wrong.
