### ISSUE TITLE
Not able to add product.

### ISSUE THREAD

**Issue by sabyasacheeroy** [stemword/php-inventory-management-system#21]
Not able to add product. Its keep on showing Loading.

**Comment by dipankardd** [comment]
Create a folder "stock' under "/assests/images/" folder and add the following line in the "php_action/createProduct.php" file
$url = '../assests/images/stock/'.uniqid(rand()).'.'.$type;

**Comment by dipankardd** [comment]
Are you working on online server or on localhost via Wamp or Xamp?

**Comment by Meet2308** [comment]
@dipankardd after creating a stock folder and change the URL inside createProduct.php it's still not working.

**Comment by stemword** [comment]
Hey Please create a stock folder in assets/images.
Give permission.
You can also check this demo for your reference

https://www.youtube.com/watch?v=9UZM8MmY1T8
