### ISSUE TITLE
store_url issue

### ISSUE THREAD

**Issue by dipankardd** [stemword/php-inventory-management-system#22]
My domain name is "myinventory.in" and I have uploaded the project in "pims" folder under root.

My db_connect.php file is having following code -
$store_url = "https://myinventory.in/pims/";

Is it correct. When I doing "https://myinventory.in/pims/" in browser after putting admin/admin as username/password it is not redirecting to the dashboard.php page instead showing login screen.

But it is perfectly working in localhost wamp server with following line in db_connect.php file
$store_url = "http://localhost/pims/";

Please let me know what to do ?

**Comment by stemword** [comment]
Can you please share code or something so I can look into it.
