### ISSUE TITLE
Product Image uploading issues

### ISSUE THREAD

**Issue by anasjaveed** [stemword/php-inventory-management-system#24]
Not able to upload product image while adding the product. Also cant upload product image while editing the product which has already been added .
While image is getting selected and while clicked save changes while adding the product , changes the save changes button to loading and is not getting saved in the database and the similar while editing the product.

**Comment by stemword** [comment]
Hey Please create a stock folder in assets/images.
You can also check this demo for your reference 

https://www.youtube.com/watch?v=9UZM8MmY1T8
