### ISSUE TITLE
Hi i can help you with development

### ISSUE THREAD

**Issue by vedaang90** [stemword/php-inventory-management-system#25]
Hi I saw your issue on freelancer.com So can you please share more details with me.
Thanks
Vedaang

**Comment by infojohn77** [comment]
Hello, 
Thank you for indicating interest in my work. Thus us what u want to do in the program.
The software is a sales and inventory program. It runs on local server e.g Wamp. 
Currently, there are few missing functions and features I want to add such as dashboard to show sales reports, debts reports, products reports(inventory) customers reports etc) NOTE: All the reports systems in the program are already working fine. Your just needs to integrate a Dashboard for it. 

I will need to add Cashiering function like Start and End of day cash balance.
Thus is a brief highlight of what will be done.

Do let me know the next step.

Thanks regards.


I want to add additional features and some users restrictions.

2.

**Comment by vedaang90** [comment]
Hey can you please send the details on my email.
***@***.***
I saw the requirements. Please share the budget and the language of this system.
Thanks
Vedaang

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vedaang90** [comment]
Hey
You didnt reply back. Please give me chance to work.
Please.
Thanks

**Comment by infojohn77** [comment]
Hello Vaadang,
I will share the existing program with you including the the source code.

I will like you to install and explore the existing features of the program.

Then I will send you the new features want to include.

Thanks and regards.

John Kelvin

**Comment by vedaang90** [comment]
I installed the code and saw the existing functionality.
Can you please share your skype.
So we can talk in detail.
Thanks
Vedaang

**Comment by infojohn77** [comment]
Hello Vedaang,
Sorry for the late reply. I have been away for some assignments. Here is my
skype ID: Johngumua.
When will you be available for a chat?

John Kelvin

**Comment by vedaang90** [comment]
Hi John
Thanks for your reply.
I have sent a message to you on Skype. Please see to it so I can start your work asap.
Thanks
Vedaang

**Comment by vedaang90** [comment]
Hi John
Shall we have a LIVE chat on skype today at 10 am nigerian time.
Please be online as Its getting too much delay for the project.
Thanks
Vedaang

**Comment by infojohn77** [comment]
Morning Vedaang,
Can you come on skype now?
I have up to an hour from free.

Regards.
