### ISSUE TITLE
Making product image optional while adding product

### ISSUE THREAD

**Issue by duraiyuvaraj** [stemword/php-inventory-management-system#4]
Some generic doesn't require product image. So it can be made optional.

**Comment by xbeowulfx** [comment]
waiting for that option also but even i am unable to add product with image

**Comment by duraiyuvaraj** [comment]
I have some dirty workaround. It doesn't qualify for public posting. I can post if interested.

**Comment by stemword** [comment]
> Some generic doesn't require product image. So it can be made optional.

Sure I'll do that and update you.

**Comment by stemword** [comment]
> waiting for that option also but even I am unable to add product with image

Please provide permission to the folder.
