### ISSUE TITLE
Great Work - This can go very far.. happy to help out.

### ISSUE THREAD

**Issue by oneprobanana** [stemword/php-inventory-management-system#6]
I got this up and running very quickly, had to assign a password in the database.

This product has a lot of potential and as a business owner I have the understanding to help with this solution.  Some things I think you need to add or work on:

-On first run, you should create a user and password.
-You need a table for customers or contacts "name email address phone company/person/vendor date added.
-You need country GST and/or VAT customization.
-Rather than removing a product when it is sold just take away from the quantity. and put it to out of stock at zero.
-you need delivery or pickup, if delivery then you need delivery address, and note and special instructions.
-on your products you need boxed product or manufactured (externally or internally.

I am happy to help out make this thing good!

**Comment by stemword** [comment]
So let's do it together.
