### ISSUE TITLE
What is the user and password?

### ISSUE THREAD

**Issue by neliobnjr** [stemword/php-inventory-management-system#7]
Hey guys, this might be a real dumb question, I can't log in. I couldn't access the inventory or find the standard password and userid.

can you help me?

thanks!

**Comment by ShubhamJulaha** [comment]
Hi @neliobnjr ,
I checked the DB and password is 21232f297a57a5a743894a0e4a801fc3
But it is MD5 encrypted.

So actual password is admin and username is also admin

Thanks

**Comment by neliobnjr** [comment]
Hi @ShubhamJulaha , thank you  so much!! Worked pretty good.
